all: 15-solver 24-solver

15-solver: 15-solver.cpp algorithms.h heuristics.h codigoHash.h
	g++ -std=gnu++0x 15-solver.cpp -o 15-solver

24-solver: 24-solver.cpp algorithms.h heuristics.h codigoHash.h
	g++ -std=gnu++0x 24-solver.cpp -o 24-solver
	
clean:	
	rm -rf *~ 15-solver 24-solver
